apiVersion: kubepattern.dev/v1
kind: Pattern
metadata:
  name: naked-pod
spec:
  displayName: "Naked Pod (Unmanaged)"
  category: "Architecture"
  severity: "MEDIUM"
  message: "Il Pod {{target.metadata.name}} nel namespace {{target.metadata.namespace}} è un 'naked pod': non è gestito da alcun controller (es. Deployment)."
  
  target:
    kind: Pod
    apiVersion: v1
    plural: pods
    filters:
      matchAll:
        - path: "metadata.ownerReferences"
          operator: IS_EMPTY
          values: []